Repository yarion1/backend-ps, pull requests merged in 2022-05, with the labels that each got.

#23 Criação da rota e do model de worker
  controllers/workerController.js
  index.js
  routes/routerWorker.js
Labels: enhancement

#22 correções nas migrates para atender a reformar do banco de dados
  config/config.json
  migrations/20220410203047-create-profission.js
  migrations/20220410203340-create-worker.js
  migrations/20220410203457-create-product-rent.js
  models/profession.js
  models/rentProduct.js
Labels: bug, enhancement

#27 Feature/it03/r39
  routes/routerProduct.js
Labels: enhancement

#20 Migrationsdobancodedados/IT03/R26
  migrations/20220425021226-create-contract.js
  models/contract.js
  package.json
Labels: enhancement

#21 Criação dos services de autenticação
  .env
  controllers/authController.js
  index.js
  middleware/auth.js
  migrations/20220410203047-create-profission.js
  migrations/20220410203340-create-worker.js
  migrations/20220410203457-create-product-rent.js
  models/profession.js
  models/rentProduct.js
  package.json
  routes/routerAuth.js
Labels: enhancement

#26 feature/IT03/R29
  controllers/categoryController.js
  index.js
  routes/routerCategory.js
Labels: enhancement

#29 Bug-fix3
  controllers/authController.js
  controllers/usersController.js
Labels: bug

#30 Feature/it03/r35
  config/config.json
  controllers/authController.js
  controllers/usersController.js
  migrations/20220405170854-create-users.js
  models/usersModel.js
  routes/routerAuth.js
Labels: enhancement

#32 feature/IT04/R51
  controllers/authController.js
  routes/routerAuth.js
Labels: enhancement

#31 Feature/it04/r46
  routes/routerProduct.js
  routes/routerRentProduct.js
Labels: enhancement

#34 feature/IT04/R52
  controllers/professionController
  index.js
  models/profession.js
  routes/routerProfession.js
Labels: enhancement

#33 Feature/it04/r54
  controllers/rentProductController.js
Labels: enhancement

#35 feature/IT04/R53
  .dockerignore
  Dockerfile
  config/config.json
  controllers/professionController.js
  controllers/usersController.js
  docker-compose.yml
  index.js
  migrations/20220405170854-create-users.js
  models/usersModel.js
  package.json
  processes.json
Labels: enhancement
